[package]
name = "hyozu"
version = "0.1.0"
edition = "2024"

[dependencies]
iced_core = "0.15.0-dev"
iced_widget = { version = "0.15.0-dev", features = ["canvas"] }
jiff = "0.2"

[dev-dependencies]
iced = { version = "0.15.0-dev", features = ["debug"] }

[workspace]
members = ["examples/*"]

[patch.crates-io]
iced = { git = "https://github.com/airstrike/iced.git", branch = "dev" }
iced_core = { git = "https://github.com/airstrike/iced.git", branch = "dev" }
iced_widget = { git = "https://github.com/airstrike/iced.git", branch = "dev" }
